library(plyr)
library(rgdal)
library(ggplot2)

setwd("C:/Users/Elisa/Documents/Woodcock_Git/R_Woodcock/DERI")

phase=c(57,48,39,30,21,14,8,3,1,1,3,8,15,24,34,45,57,
        68,78,86,93,98,100,100,98,95,89,82,74,66, 57)
d=read.csv("C:/Users/Elisa/Documents/Woodcock_Git/R_Woodcock/January.csv")

mp=cbind(phase, d)
mp$date=strptime(paste(d[,1]),"%m/%d/%Y")
mp$date=format(mp$date, "%m/%d/%Y")


##takes all files with ".csv" ending and stores to obj
fileNames <- Sys.glob("*.csv")
fileNames
df=ldply(fileNames, read.csv)
head(df)

##conversions to df
df$Latitude=as.numeric(as.character(df$Latitude))
df$Longitude=as.numeric(as.character(df$Longitude))
##Create datetime column 
df$gmt=strptime(paste(df$GMT.Time),"%m/%d/%Y %H:%M")
df$dt=df$gmt-(60*60*6)
df$date=format(df$dt, "%m/%d/%Y")
df$mp = as.character(1)


##adding moon phase to dataframe
for (i in 1:nrow(df)){
  for (j in 1:nrow(mp)){
    if (df$date[i] == mp$date[j]){
      df$mp[i]=mp$phase[j]
    }
  }
}

############################################
##adding high temperature
high_jan = c(47, 50, 60, 58, 51, 63, 64,
         61, 63, 48, 52, 61, 63, 60,
         72, 59, 55, 59, 65, 71, 73,
         45, 52, 59, 71, 62, 51, 62, 
         73, 74, 77)


for (i in 1:length(df$date)){
  #browser()
  j = paste(df$date[i])
  k = as.numeric(substr(j, 4, 5))
  df$high[i] = as.integer(high_jan[k])
}


############################################
##adding individual data

##fixing banding data
bd=read.csv("C:/Users/Elisa/Documents/Woodcock/Banding_2016_CSV.csv", header=TRUE)
#tail(bd)
levels(bd$Site)[7] <- "BOYC"
levels(bd$Freq.ID)[52] <- 149.420
##bird was released with no band
b_bird=c(167, 123, NA, "BOYC", "M", NA, NA, NA, NA, NA, "G", NA, NA, NA, NA, NA)
##boyce adding in
b_bird2=c(168, 157382985, NA, "BOYC", "M", "AHY", NA, NA, NA, NA, "G", 149.420, NA, NA, NA, NA)

##adding to dataframe
bd=rbind(bd, b_bird)
bd=rbind(bd, b_bird2)


##matching data by ID and adding to df
for (i in 1:nrow(df)){
  m = df$BandNmbr[i]
    for (j in 1:nrow(bd)){
      if (m == bd$Band.Number[j]){
        #arr_site[i] = as.character(bd$Site[j])
        df$site[i] = as.character(bd$Site[j])
        df$weight[i] = bd$Weight[j]
        df$age[i] = as.character(bd$Age[j])
        df$sex[i] = as.character(bd$Sex[j])
      }
    } 
}

##adding in precipitation

precip_jan = c(0.01, 0, 0, 0, 0, 0, 0.43, 2.13, 
               0.01,  0, 0, 0, 0, 0, 0, 0, 0, 0,
               0, 0, 0.6,  0, 0, 0, 0, 0.92,  0,
               0, 0, 0, 0)


for (i in 1:nrow(df)){
  #browser()
  j = paste(df$date[i])
  k = as.numeric(substr(j, 4, 5))
  df$precip[i] = precip_jan[k]
}


write.csv(df, file="C:/Users/Elisa/Documents/Woodcock_Git/R_Woodcock/data_frame_export_ALL.csv")



##cleaning up df
##remove extra columns (not needed for proj analysis)
##remove non-fixes
df$Duration <- NULL
df$DOP <- NULL
df$Satellites <- NULL
df$GMT.Time <- NULL
df$weight <- NULL
om <- with(df, (Latitude==0.00000))
df <-df[!om,]

##limiting to one site for project
test= df[which(df$site=="DERI"),]

##to upload to GIS to get field/not field into attributes
write.csv(test, file="C:/Users/Elisa/Documents/Woodcock_Git/R_Woodcock/DERI_export_GIS.csv")

##conversions in GIS
##reread in data
dfg = read.csv("C:/Users/Elisa/Documents/Woodcock_Git/R_Woodcock/DERI_Field.csv")

names(dfg)[names(dfg)=="Field"] <- "field"

##building models
##field is column generated by GIS
##site not included b/c most usable data from DERI
##ID in each model such that they fall equal

fit1 <- glm(dfg$field~1, family=binomial)
fit2 <- glm(dfg$field~dfg$BandNmbr, family=binomial) ##ID only
fit3 <-glm(dfg$field~dfg$mp*dfg$BandNmbr, family=binomial) ##moonphase
fit4 <- glm(dfg$field~dfg$sex*dfg$BandNmbr, family=binomial) ##sex
fit5 <- glm(dfg$field~dfg$age*dfg$BandNmbr, family=binomial) ##age
fit6 <- glm(dfg$field~dfg$high*dfg$BandNmbr, family=binomial) ##temp
fit7 <- glm(dfg$field~dfg$precip*dfg$high*dfg$ID, family=binomial) #precip*temp
fit8 <- glm(dfg$field~dfg$age*dfg$sex*dfg$ID, family=binomial) ##age*sex



K = c(length(coef(fit1)), length(coef(fit2)), length(coef(fit3)), length(coef(fit4)),
    length(coef(fit5)),length(coef(fit6)), length(coef(fit7)), length(coef(fit8)))
n = nrow(dfg)
LL = c(logLik(fit1), logLik(fit2), logLik(fit3), logLik(fit4), logLik(fit5),
       logLik(fit6), logLik(fit7), logLik(fit8))
AICc =-2*LL + 2*K*(n/(n-K-1))

wc.res = data.frame(model = 1:8,
                       LogLik = LL,
                       Rank = rank(AICc),
                       AICc)

vars = c("intercept", "ID", "moonphase", "sex", "age", "temp", "precip*temp", "age*sex")

wc.res=cbind(wc.res, vars)


tt = wc.res
order(tt$Rank, decreasing=TRUE)
?reorder()
?order
str(tt)
wc.res = tt[order(tt$Rank),]




